branch-defaults:
  master:
    environment: image-filter-starter-code-dev7
    group_suffix: null
deploy:
  artifact: ./www/Archive.zip
global:
  application_name: image-filter-starter-code2
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 12
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
